### ISSUE TITLE
Support for Custom Similarity Calculations

### ISSUE THREAD

**Issue by emersonlebleu** [anergictcell/hpo3#4]
Our team is using your library in our research. In particular one of our graduate students has been using the pyhpo package and the ability to create custom similarity scores. The performance of the rust implemented package is impressive and we would love to utilize it. We would also like to take advantage of the ease of use that comes with python (and this package) if possible.

Do you have any plans to implement any kind of similarity score customization for this library? I've looked over both repos (hpo and hpo3) and could fork and them add our algorithm to the appropriate sections for our own use if that would be best for you.

But before I went that route, I just wanted to see if you had any desire or had thought about the custom similarity scores for this library. Given it is rust implemented I see how that would be challenging to make flexible. 

My thinking was that the algorithms would still need to be implemented and compiled in rust but then that maybe there could be a function like custom_similarity & custom_similarity_scores that could be used from the python interface and linked to a compiled custom score function. _I'm not by any means a rust expert so that could be a dumb idea_.

**Somewhat more complicated than my just forking the repo so let me know if you think that implementing custom scoring functionality doesn't seem feasible and I'll just make some modifications for our own use?**

**Comment by anergictcell** [comment]
You're bringing up a very good point. I was thinking about how to best allow custom similarity algorithms, but could not find a way to support this, especially across the Python/Rust border. It would be great to have that feature, even allowing Python code as a custom similarity calculation. If you have any idea, I'd be happy to implement this or work on this together.

As an alternative I can offer to add your similarity algorithm to `hpo` and expose it also in hpo3. You can create a pull request to add the algorithm to hpo and then I will include it also in hpo3. It would be great to have more similarity scores available for users in hpo and hpo3.

**Comment by emersonlebleu** [comment]
Thanks for getting back to me so quickly. I may try to test my suggested approach with a "toy" set of functions and see if my idea for implementation works at all with the rust/python flow. 

In terms of adding the similarity algorithm I'll need to talk to the student who's algorithm it is to be sure she would be comfortable with it being available as it is if so I can point you to or provide the rust source for the algorithm. I'll let you know how this progresses.

**Comment by anergictcell** [comment]
I looked a bit into the issue and there is a way to pass a Python method to Rust and call it from there. Using this, I created an API that could work like this:

```python
from pyhpo import Ontology
Ontology()

# define a custom similarity method in Python
def mysim(term1, term2):
    return (len(term1.name) + len(term2.name)) / 2.0

term_a = Ontology[123]
term_b = Ontology[456]

term_a.custom_similarity_score(term_b, mysim)
```

Would that work for you? I could also try to include this method in the parallel constructor, so that it can be run in parallel. However, please note that this will be much much slower than native Rust similarity methods. It might actually be faster to simply implement this on Python side fully. I'm also not sure how well the parallel implementation will work, due to issues with the GIL.

**Comment by emersonlebleu** [comment]
This could be a solution, but I wonder about the performance. I've tested our algorithm with your rust package and it is so much faster. We are building a real time web app and need as much speed for this as we can have. I am going to talk to our graduate student tomorrow about maybe adding her algorithm as one of the ones that are implemented in rust and able to be used from the python wrapper. 

However, this particular solution you're suggesting above may be useful for others who's algorithm isn't computationally expensive? So it may be something other users might like?

**Comment by emersonlebleu** [comment]
I just wanted to update you that our team has decided to build the backend of our application in rust so that we can leverage the speed of the native rust package. This can be closed if you would like to not work on this enhancement.

**Comment by anergictcell** [comment]
Thanks for the update. If you decide to open-source your similarity method, please let me know. I will then include it in the hpo package.
