### ISSUE TITLE
similarities_scores BMA function not working well

### ISSUE THREAD

**Issue by ivanwilliammd** [anergictcell/hpo3#6]
Dear @anergictcell , 

Thank you really much for creating a great multithreading library for HPO
I would like to report that the HPOSet `similarity_scores(other, kind, method, combine)`

doesn't allow BMA type combine method, and only accept funSimMax / funSimAvg instead
The method I use is the default graphic based

Thank you

**Comment by ivanwilliammd** [comment]
After further check --> it seams the correct term would be BWA not BMA

**Comment by anergictcell** [comment]
Hi @ivanwilliammd ,

Thanks for reporting this issue. The correct name is actually `bma`. That's how it's called in [pyhpo](https://pyhpo.readthedocs.io/en/stable/set.html#similarity) and also in the description of the method in [hpo](https://docs.rs/hpo/latest/hpo/similarity/enum.StandardCombiner.html#variant.Bwa). 

I will fix this in the upstream [hpo](https://crates.io/crates/hpo) crate and make an update of [hpo3](https://pypi.org/project/hpo3/) in the next days as well.

**Comment by anergictcell** [comment]
Fixed upstream with [this commit](https://github.com/anergictcell/hpo/commit/bb34a2c2e2af82724186ba211327304c65a038e3) in [version 0.9.1](https://crates.io/crates/hpo/0.9.1).

Also fixed in `hpo3` in [Version 1.2.0](https://pypi.org/project/hpo3/1.2.0/)
