### ISSUE TITLE
Error when using external Ontology

### ISSUE THREAD

**Issue by ivanwilliammd** [anergictcell/hpo3#8]
Previously at v1.1.0 there are no problem when doing the external ontology import
```Ontology(ontology_path)``` or ```Ontology(os.path.join(os.getcwd(), 'phenotype', 'rawdl_20240310'))```

On v1.2.0 there are problem of PanicException
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }

do you possible there were some issue causing this @anergictcell ?

**Comment by ivanwilliammd** [comment]
Current solution I use is to declare non args Ontology() first 

``Ontology()
Ontology(os.path.join(os.getcwd(), 'phenotype', 'rawdl_20240310'))```

**Comment by ivanwilliammd** [comment]
Sorry, just read your commit and it seems you change the data raw source from  ```phenotype_to_genes.txt``` to ```genes_to_phenotypes.txt```

After using it in the masterdata folder, the application run smoothly

**Comment by anergictcell** [comment]
I saw you closed this already, but thanks for the feedback anyway. I will introduce better error messages in the next update, so people don't need to check the commit history to find out what went wrong :) Sorry for the mess.
I have to update the underlying `hpo` crate first, though, so it will take a few weeks

**Comment by ivanwilliammd** [comment]
Thanks @anergictcell ... Btw do you have some paper I could cite?

**Comment by anergictcell** [comment]
I always postponed writing a paper, but would love to do so at one point. I'm missing a good use-case to describe the accuracy of predictions and similarity scores at the moment. If you have a good use-case, I'd be happy to work together on a paper.

In the meantime simply cite by pointing either to github, PyPI or the readthedocs page. Feel free to mention my real name (Jonas Marcello), whatever you prefer.

**Comment by ivanwilliammd** [comment]
Got it, thank you for letting me know... For now, I will cite the GitHub pages first.
Thanks
