### ISSUE TITLE
Gene to Omim disease associations

### ISSUE THREAD

**Issue by JakeHagen** [anergictcell/hpo3#9]
Hello

Thank you for this great library. I am really enjoying working with it so far.

Is it possible to get the diseases associated with a gene from OMIM from the Ontology object?
For example the gene IDS is associated with Mucopolysaccharidosis II (ID#309900). 

Thank You!
Jake

**Comment by anergictcell** [comment]
Hi Jake,

Currently that's not possible. In theory, this could be added. It would need to be added to the [hpo](https://github.com/anergictcell/hpo) Rust library, as the data parsing is happening there.
I'm not sure when I would find the time to implement this myself, but if you're interested in doing it yourself, that would be great. I'd be happy to help by pointing you in the best direction to start and discuss options.

**Comment by JakeHagen** [comment]
Thank for the response. I will probably try to do the mapping outside of your library as a first pass but would love to contribute it back eventually.
